import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/themes-providers'
import { cn } from '@/lib/utils'
const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Creatse Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={cn(font.className,
        "bg-white dark:bg-[#313338]")}>
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem={true}
        storageKey="discordclone"
        >
        {children}
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
